### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by abhijithrajan** [USGS-Astrogeology/autocnet#272]
Hi there,

I would like to the Ciratefi implementation to do some template matching. I installed the autocnet package using the instructions provided on the Github page, but have an error when I try to import autocnet. I believe it is caused by the fiona package, similar issue as https://github.com/conda-forge/fiona-feedstock/issues/13.  

>>> import autocnet
/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/autocnet/__init__.py", line 11, in <module>
    import autocnet.graph
  File "/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/autocnet/graph/__init__.py", line 1, in <module>
    from . import edge
  File "/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/autocnet/graph/edge.py", line 12, in <module>
    from autocnet.graph.node import Node
  File "/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/autocnet/graph/node.py", line 15, in <module>
    from autocnet.cg import cg
  File "/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/autocnet/cg/cg.py", line 6, in <module>
    import geopandas as gpd
  File "/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/arajan/anaconda3/envs/matcher/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libpoppler.71.dylib
  Referenced from: /Users/arajan/anaconda3/envs/matcher/lib/libgdal.20.dylib
  Reason: image not found

**Comment by jlaura** [comment]
@abhijithrajan Wonderful timing!  I was just working on this issue this morning. You are spot on that the conflict is with fiona (and gdal). Here is a fix that I need to PR in.  Copy the below into an environment.yml

```yaml
name: autocnet
channels:
  - conda-forge
  - usgs-astrogeology
  - menpo
dependencies:
  - python >= 3
  - coveralls
  - csmapi
  - cyvlfeat
  - geoalchemy2
  - geopandas
  - imageio
  - knoten
  - ncurses
  - networkx
  - numpy
  - opencv
  - pillow
  - pip:
    - redis
  - plio >= 1.1.0
  - plurmy
  - pyproj
  - pytest
  - pytest-cov
  - scikit-image
  - scipy
  - shapely
  - sqlalchemy
  - vlfeat
```

Then execute `conda create env -f environment.yml`. This will create a working autocnet environment that can be conda activated (`conda activate autocnet`). Then you can `cd` into the autocnet directory and `python setup.py install`. Alternatively, you can add `autocnet` to the environment.yml file above before creating the environment.

We have also been struggling with GDAL as the conda package manager loves to downgrade GDAL and break the library linking. 

Let me know how this works for you.
